networks:
  local-network:
    driver: bridge
    name: infra_network
    external: false

services:
  # pg 管理工具
  pgadmin:
    image: dpage/pgadmin4:9.1.0
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      TZ: Asia/Shanghai
      PGADMIN_DEFAULT_EMAIL: admin@qq.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - local-network
